service: nodeless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: rocketnodeserverless
    events:
      - s3:
          bucket: rocketnodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: rocketnodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
